language: node_js

node_js:
  - '10'

sudo: false
if: tag IS blank

branches:
  only:
    - master

install:
  - npm i

script:
  - npm install codecov -g
  - npm run test
  - npm run lint
  - npm run build

after_success:
  - codecov
  - npm i -g semantic-release@15 @semantic-release/npm
    @semantic-release/changelog @semantic-release/git
    @semantic-release/changelog @semantic-release/commit-analyzer
    @semantic-release/release-notes-generator
  - npx semantic-release
